let products = JSON.parse(localStorage.getItem('products')) || [];

let pedido = [];

let editingIndex = null;

const productsGrid = document.getElementById('productsGrid');
const pedidoItems = document.getElementById('pedidoItems');

function renderProducts(filtered = products){

  productsGrid.innerHTML = '';

    filtered.forEach((product,index)=>{

        productsGrid.innerHTML += `

              <div class="card">

                      <img src="${product.image}" alt="produto">

                              <div class="card-content">

                                        <h3>${product.name}</h3>

                                                  <div class="price">
                                                              R$ ${Number(product.price).toFixed(2)}
                                                                        </div>

                                                                                  <div class="category">
                                                                                              ${product.category}
                                                                                                        </div>

                                                                                                                  <div class="card-buttons">

                                                                                                                              <button class="btn green" onclick="addPedido(${index})">
                                                                                                                                            Adicionar
                                                                                                                                                        </button>

                                                                                                                                                                    <button class="btn blue" onclick="editProduct(${index})">
                                                                                                                                                                                  Editar
                                                                                                                                                                                              </button>

                                                                                                                                                                                                          <button class="btn red" onclick="deleteProduct(${index})">
                                                                                                                                                                                                                        Excluir
                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                `;

                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                  function renderPedido(){

                                                                                                                                                                                                                                                                    pedidoItems.innerHTML = '';

                                                                                                                                                                                                                                                                      let total = 0;

                                                                                                                                                                                                                                                                        pedido.forEach((item,index)=>{

                                                                                                                                                                                                                                                                            total += item.price * item.qtd;

                                                                                                                                                                                                                                                                                pedidoItems.innerHTML += `

                                                                                                                                                                                                                                                                                      <div class="pedido-item">

                                                                                                                                                                                                                                                                                              <div>

                                                                                                                                                                                                                                                                                                        <strong>${item.name}</strong><br>
                                                                                                                                                                                                                                                                                                                  QTD: ${item.qtd}

                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                  <div>

                                                                                                                                                                                                                                                                                                                                            R$ ${(item.price * item.qtd).toFixed(2)}

                                                                                                                                                                                                                                                                                                                                                      <button class="btn red" onclick="removePedido(${index})">
                                                                                                                                                                                                                                                                                                                                                                  X
                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                              `;

                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('pedidoTotal').innerText = total.toFixed(2);
                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('pedidoTotalBottom').innerText = total.toFixed(2);

                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                    function addPedido(index){

                                                                                                                                                                                                                                                                                                                                                                                                      const product = products[index];

                                                                                                                                                                                                                                                                                                                                                                                                        const existing = pedido.find(item => item.name === product.name);

                                                                                                                                                                                                                                                                                                                                                                                                          if(existing){

                                                                                                                                                                                                                                                                                                                                                                                                              existing.qtd++;

                                                                                                                                                                                                                                                                                                                                                                                                                }else{

                                                                                                                                                                                                                                                                                                                                                                                                                    pedido.push({
                                                                                                                                                                                                                                                                                                                                                                                                                          name:product.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                price:Number(product.price),
                                                                                                                                                                                                                                                                                                                                                                                                                                      qtd:1
                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                              renderPedido();

                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                              function removePedido(index){

                                                                                                                                                                                                                                                                                                                                                                                                                                                pedido.splice(index,1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderPedido();

                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                  function limparPedido(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                    pedido = [];

                                                                                                                                                                                                                                                                                                                                                                                                                                                      renderPedido();

                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                      function openModal(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('modal').style.display = 'flex';

                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        function closeModal(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.getElementById('modal').style.display = 'none';

                                                                                                                                                                                                                                                                                                                                                                                                                                                            clearFields();

                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            function clearFields(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById('productName').value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('productPrice').value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('productCategory').value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('productImage').value = '';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function saveProduct(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const name = document.getElementById('productName').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const price = document.getElementById('productPrice').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const category = document.getElementById('productCategory').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const imageInput = document.getElementById('productImage');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if(!name || !price || !category){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alert('Preencha todos os campos!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const file = imageInput.files[0];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(file){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const reader = new FileReader();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reader.onload = function(e){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const image = e.target.result;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(editingIndex !== null){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        products[editingIndex] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                editingIndex = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }else{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              products.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          saveLocal();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reader.readAsDataURL(file);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function saveLocal(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      localStorage.setItem('products',JSON.stringify(products));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderProducts();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          closeModal();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function deleteProduct(index){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(confirm('Excluir produto?')){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                products.splice(index,1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    saveLocal();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function editProduct(index){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const product = products[index];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.getElementById('productName').value = product.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('productPrice').value = product.price;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById('productCategory').value = product.category;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                editingIndex = index;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  openModal();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('searchInput').addEventListener('input',function(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const value = this.value.toLowerCase();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const filtered = products.filter(product =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          product.name.toLowerCase().includes(value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              renderProducts(filtered);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.onclick = function(event){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const modal = document.getElementById('modal');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if(event.target === modal){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      closeModal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderProducts();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderPedido();