let products = JSON.parse(localStorage.getItem('products')) || [];

let editingIndex = null;

const productsGrid = document.getElementById('productsGrid');
const totalValue = document.getElementById('totalValue');
const emptyMessage = document.getElementById('emptyMessage');

function renderProducts(filteredProducts = products){

    productsGrid.innerHTML = '';

        if(filteredProducts.length === 0){
                emptyMessage.style.display = 'block';
                    }else{
                            emptyMessage.style.display = 'none';
                                }

                                    let total = 0;

                                        filteredProducts.forEach((product,index)=>{

                                                total += Number(product.price);

                                                        productsGrid.innerHTML += `
                                                                
                                                                        <div class="card">

                                                                                    <img src="${product.image}" alt="Produto">

                                                                                                <div class="card-content">

                                                                                                                <h3>${product.name}</h3>

                                                                                                                                <div class="price">
                                                                                                                                                    R$ ${Number(product.price).toFixed(2)}
                                                                                                                                                                    </div>

                                                                                                                                                                                    <div class="category">
                                                                                                                                                                                                        ${product.category}
                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                        <div class="card-buttons">

                                                                                                                                                                                                                                                            <button class="btn edit-btn" onclick="editProduct(${index})">
                                                                                                                                                                                                                                                                                    Editar
                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                            <button class="btn delete-btn" onclick="deleteProduct(${index})">
                                                                                                                                                                                                                                                                                                                                                    Excluir
                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                    `;
                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                            totalValue.innerText = total.toFixed(2);

                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                            function openModal(){

                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('productModal').style.display = 'flex';

                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                function closeModal(){

                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('productModal').style.display = 'none';

                                                                                                                                                                                                                                                                                                                                                                                                                                        clearFields();

                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                        function clearFields(){

                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('productName').value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('productPrice').value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('productCategory').value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('productImage').value = '';

                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        function saveProduct(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const name = document.getElementById('productName').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const price = document.getElementById('productPrice').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const category = document.getElementById('productCategory').value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const imageInput = document.getElementById('productImage');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(!name || !price || !category){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert('Preencha todos os campos!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const file = imageInput.files[0];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(file){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const reader = new FileReader();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reader.onload = function(e){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const image = e.target.result;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(editingIndex !== null){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                products[editingIndex] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                editingIndex = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }else{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            products.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    saveToLocalStorage();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reader.readAsDataURL(file);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }else{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(editingIndex !== null){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            products[editingIndex] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...products[editingIndex],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            category
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    editingIndex = null;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                saveToLocalStorage();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }else{

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert('Selecione uma imagem!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function saveToLocalStorage(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    localStorage.setItem('products',JSON.stringify(products));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderProducts();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            closeModal();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function deleteProduct(index){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(confirm('Deseja excluir este produto?')){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        products.splice(index,1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                saveToLocalStorage();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function editProduct(index){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const product = products[index];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('productName').value = product.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('productPrice').value = product.price;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('productCategory').value = product.category;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        editingIndex = index;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('modalTitle').innerText = 'Editar Produto';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                openModal();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('searchInput').addEventListener('input',function(){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const value = this.value.toLowerCase();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const filtered = products.filter(product =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                product.name.toLowerCase().includes(value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderProducts(filtered);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.onclick = function(event){

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const modal = document.getElementById('productModal');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(event.target === modal){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        closeModal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            renderProducts();